name: Export Solution

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Debug Vars
        run: |
          echo "CLIENTID=${{ vars.CLIENTID }}"
          echo "TENANTID=${{ vars.TENANTID }}"
          echo "DEV_URL=${{ vars.DEV_URL }}"

      - name: Export Solution (Managed)
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.DEV_URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          managed: true
          solution-output-file: "${{ runner.temp }}/DemoSolution_managed.zip"
          run-asynchronously: true
          overwrite: true

      - name: Upload Exported Solution
        uses: actions/upload-artifact@v4
        with:
          name: exported-solution
          path: "${{ runner.temp }}/DemoSolution_managed.zip"
