name: Export From DEV

on:
  workflow_dispatch:

jobs:
  Export:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: DemoSolution

      - name: Export Solution - Unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: DemoSolution
          solution-output-file: "${{ runner.temp }}/exported/DemoSolution.zip"
          managed: false
          run-asynchronously: true
          overwrite: true

      - name: Export Solution - Managed
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-name: DemoSolution
          solution-output-file: "${{ runner.temp }}/exported/DemoSolution_managed.zip"
          managed: true
          run-asynchronously: true
          overwrite: true

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: '${{ runner.temp }}/exported/DemoSolution.zip'
          solution-folder: 'PowerPlatform/Solutions/DemoSolution'
          solution-type: 'Both'
          overwrite-files: true

      - name: Commit Changes to Repo
        run: |
          git config user.email "Atewogboye.T@Gmail.com"
          git config user.name "${{ github.actor }}"
          git add 'PowerPlatform/Solutions/DemoSolution' --all
          git commit -m "DemoSolution Changes" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: '${{ runner.temp }}/packed/DemoSolution_Managed.zip'
          solution-folder: 'PowerPlatform/Solutions/DemoSolution'
          solution-type: 'Managed'
          overwrite-files: true

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: '${{ runner.temp }}/packed/**'
          overwrite: true
