name: Import Solution
on:
  workflow_run:
    workflows: ["Export Solution"]
    types: [completed]

jobs:
  import:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Debug Vars
        run: |
          echo "QA_URL=${{ vars.QA_URL }}"
          echo "CLIENTID=${{ vars.CLIENTID }}"
          echo "TENANTID=${{ vars.TENANTID }}"
          
      - name: Download Exported Solution
        uses: actions/download-artifact@v4
        with:
          name: exported-solution
          path: "${{ runner.temp }}/import"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.QA_URL }}
          app-id: ${{ vars.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ vars.TENANTID }}
          solution-file: "${{ runner.temp }}/import/DemoSolution_managed.zip"
          activate-plugins: true
          run-asynchronously: true
