name: Import Solution
on:
  workflow_run:
    workflows: ["Export Solution"]
    types: [completed]

jobs:
  import:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Debug Vars
        run: |
          echo "QA_URL=${{ vars.QA_URL }}"
          echo "CLIENTID=${{ vars.CLIENTID }}"
          echo "TENANTID=${{ vars.TENANTID }}"
          
      - name: Download Exported Solution
        uses: actions/download-artifact@v4
        with:
          name: exported-solution
          path: "${{ runner.temp }}/import"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
